package br.com.views;

import br.com.dao.model.ConstituentSystemDAO;
import br.com.object.model.ConstituentSystem;
import br.com.table.model.ConstituentSystemTableModel;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class CadastrarCS extends javax.swing.JFrame {
    
    ConstituentSystemTableModel eTableModel;
    ConstituentSystemDAO cDAO;
    private ConstituentSystem exu;
    
    public CadastrarCS() {
        initComponents();
        jlabelActive.setVisible(false);
        jlabelAuthentication.setVisible(false);
        jlabelName.setVisible(false);
        jlabelServerAddress.setVisible(false);
        tfieldName.setVisible(false);
        tfieldServerAddress.setVisible(false);
        tareaAuthentication.setVisible(false);
        jcomboboxActive.setVisible(false);
        jButtonOk.setVisible(false);
        jPanelCS.setVisible(false);
        editarB.setVisible(false);
        eTableModel = new ConstituentSystemTableModel();
        cDAO = new ConstituentSystemDAO();
        //initComponents();
        configureTables();
    }
    
    private void configureTables() {
        List<ConstituentSystem> listCS = new ArrayList<>();
        listCS = cDAO.getAll();
        
        if (listCS.size() > 0) {
            eTableModel.addListCS(listCS);
            tableCS.setModel(eTableModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonEdit = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        jPanelCS = new javax.swing.JPanel();
        jlabelServerAddress = new javax.swing.JLabel();
        jlabelAuthentication = new javax.swing.JLabel();
        jlabelName = new javax.swing.JLabel();
        jlabelActive = new javax.swing.JLabel();
        jcomboboxActive = new javax.swing.JComboBox<>();
        jButtonOk = new javax.swing.JButton();
        tfieldName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tareaAuthentication = new javax.swing.JTextArea();
        tfieldServerAddress = new javax.swing.JTextField();
        editarB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCS = new javax.swing.JTable();
        buttonRemove1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("Catalog of Trusted Systems");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 50, 317, 32);

        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(240, 90, 328, 10);

        buttonEdit.setBackground(new java.awt.Color(255, 255, 255));
        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/views/document_edit.png"))); // NOI18N
        buttonEdit.setText("Edit CS");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEdit);
        buttonEdit.setBounds(500, 360, 130, 40);

        buttonAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/views/mais.png"))); // NOI18N
        buttonAdicionar.setText("Add CS");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAdicionar);
        buttonAdicionar.setBounds(200, 360, 130, 40);

        jLabel2.setText("Table of registred Constituents Systems");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 180, 300, 14);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextField2.setText("Below are listed all the registred trusted systems that can parcipate of a SoS and the SoS Admin can add ou remove CS.");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 110, 740, 40);

        name4.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        name4.setText("Description:");
        getContentPane().add(name4);
        name4.setBounds(30, 120, 77, 17);

        jPanelCS.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCS.setBorder(javax.swing.BorderFactory.createTitledBorder("Constituent System"));

        jlabelServerAddress.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jlabelServerAddress.setText("Server Address:");

        jlabelAuthentication.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jlabelAuthentication.setText("Authentication:");

        jlabelName.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jlabelName.setText("Name:");

        jlabelActive.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jlabelActive.setText("Active:");

        jcomboboxActive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.active}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCS, eLProperty, jcomboboxActive);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableCS, org.jdesktop.beansbinding.ELProperty.create("${selectedElement!=null}"), jcomboboxActive, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        jButtonOk.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/views/Yes_check2.png"))); // NOI18N
        jButtonOk.setText("Ok!");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        tareaAuthentication.setColumns(20);
        tareaAuthentication.setRows(5);
        jScrollPane4.setViewportView(tareaAuthentication);

        editarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/views/Yes_check2.png"))); // NOI18N
        editarB.setText("Ok!");
        editarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCSLayout = new javax.swing.GroupLayout(jPanelCS);
        jPanelCS.setLayout(jPanelCSLayout);
        jPanelCSLayout.setHorizontalGroup(
            jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCSLayout.createSequentialGroup()
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelServerAddress)
                            .addComponent(jlabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfieldName)
                            .addComponent(tfieldServerAddress)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCSLayout.createSequentialGroup()
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCSLayout.createSequentialGroup()
                                .addComponent(jlabelActive)
                                .addGap(59, 59, 59))
                            .addGroup(jPanelCSLayout.createSequentialGroup()
                                .addComponent(jlabelAuthentication)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCSLayout.createSequentialGroup()
                                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editarB))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addGroup(jPanelCSLayout.createSequentialGroup()
                                .addComponent(jcomboboxActive, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        jPanelCSLayout.setVerticalGroup(
            jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCSLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelName)
                    .addComponent(tfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCSLayout.createSequentialGroup()
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelServerAddress)
                            .addComponent(tfieldServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlabelAuthentication))
                    .addGroup(jPanelCSLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcomboboxActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelActive))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(editarB))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanelCS);
        jPanelCS.setBounds(200, 420, 430, 290);

        tableCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tableCS);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 210, 810, 140);

        buttonRemove1.setBackground(new java.awt.Color(255, 255, 255));
        buttonRemove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/views/menos.png"))); // NOI18N
        buttonRemove1.setText("Remove CS");
        buttonRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemove1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRemove1);
        buttonRemove1.setBounds(350, 360, 130, 40);

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        limpaCampos();
        jlabelActive.setVisible(true);
        jlabelAuthentication.setVisible(true);
        jlabelName.setVisible(true);
        jlabelServerAddress.setVisible(true);
        jButtonOk.setVisible(true);
        jPanelCS.setVisible(true);
        editarB.setVisible(false);
        tfieldName.setVisible(true);
        tfieldServerAddress.setVisible(true);
        tareaAuthentication.setVisible(true);
        jcomboboxActive.setVisible(true);

        //ConstituentSystem cs = new ConstituentSystem();
        //lstCS.add(cs);
        //int nLinhas = jTable1.getRowCount() - 1;
        //jTable1.setRowSelectionInterval(nLinhas, nLinhas);
        //jlabelName.requestFocus();
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        jlabelActive.setVisible(true);
        jlabelAuthentication.setVisible(true);
        jlabelName.setVisible(true);
        jlabelServerAddress.setVisible(true);
        editarB.setVisible(true);
        jPanelCS.setVisible(true);
        jButtonOk.setVisible(false);
        
        tfieldName.setVisible(true);
        tfieldServerAddress.setVisible(true);
        tareaAuthentication.setVisible(true);
        jcomboboxActive.setVisible(true);
        
        tfieldName.setText(tableCS.getValueAt(tableCS.getSelectedRow(), 1).toString());
        tfieldServerAddress.setText(tableCS.getValueAt(tableCS.getSelectedRow(), 2).toString());
        tareaAuthentication.setText(tableCS.getValueAt(tableCS.getSelectedRow(), 3).toString());
        jcomboboxActive.setSelectedItem(tableCS.getValueAt(tableCS.getSelectedRow(), 4));
        

    }//GEN-LAST:event_buttonEditActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // fazendo a validação dos dados 
        if ((tfieldName.getText().isEmpty()) || (tfieldServerAddress.getText().isEmpty()) || (tareaAuthentication.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "The fields can not return empty");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            //ConstituentSystem cs = new ConstituentSystem(tfieldName.getText(), Integer.parseInt(tfieldServerAddress.getText()), tareaAuthentication.getText(), Boolean.parseBoolean(jcomboboxActive.getSelectedItem().toString()));
            ConstituentSystem cs = new ConstituentSystem();
            cs.setName(tfieldName.getText());
            cs.setServerAddress(tfieldServerAddress.getText());
            cs.setAuthentication(tareaAuthentication.getText());
            cs.setActive(Boolean.parseBoolean(jcomboboxActive.getSelectedItem().toString()));
            ConstituentSystemDAO csDAO = new ConstituentSystemDAO();
            csDAO.save(cs);
            eTableModel.removeAll();
            eTableModel.addListCS(cDAO.getAll());
            repaint();
            //JOptionPane.showMessageDialog(null, "Constituent System " + tfieldName.getText() + " successfully added!!!");
        }
        // apaga os dados preenchidos nos campos de texto 
        limpaCampos();
    }//GEN-LAST:event_jButtonOkActionPerformed
 private void limpaCampos(){
     tfieldName.setText("");
        tfieldServerAddress.setText("");
        tareaAuthentication.setText("");
 }
    private void buttonRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemove1ActionPerformed
        cDAO.delete(eTableModel.getCS(tableCS.getSelectedRow()));
        eTableModel.removeAll();
        eTableModel.addListCS(cDAO.getAll());
        repaint();
    }//GEN-LAST:event_buttonRemove1ActionPerformed

    private void editarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBActionPerformed
        //eTableModel.addListCS(cDAO.getAll());
        //ConstituentSystemDAO csDAO = new ConstituentSystemDAO();
        //csDAO.getAll(1, );
        //String valor = tableCS.getValueAt(tableCS.getSelectedRow(), 0).toString();
        //String SQL = "UPDATE constituentSystem SET name="++"";
        
        ConstituentSystem cs = eTableModel.getCS(tableCS.getSelectedRow());        
        cs.setName(tfieldName.getText());
        cs.setServerAddress(tfieldServerAddress.getText());
        cs.setAuthentication(tareaAuthentication.getText());
        cs.setActive(Boolean.parseBoolean(jcomboboxActive.getSelectedItem().toString()));
        
        cDAO.updateObject(cs);
        
        eTableModel.removeAll();
        eTableModel.addListCS(cDAO.getAll());
        repaint();
        limpaCampos();
        //JOptionPane.showConfirmDialog(null, valor);
    }//GEN-LAST:event_editarBActionPerformed

    /*public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"ID", "Nome", "Sigla"};
        
        conecta.executaSQL(SQL);
        conecta.rs.first();
        do{
            
        }while(conecta.rs.next());
     }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove1;
    private javax.swing.JButton editarB;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelCS;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcomboboxActive;
    private javax.swing.JLabel jlabelActive;
    private javax.swing.JLabel jlabelAuthentication;
    private javax.swing.JLabel jlabelName;
    private javax.swing.JLabel jlabelServerAddress;
    private javax.swing.JLabel name4;
    private javax.swing.JTable tableCS;
    private javax.swing.JTextArea tareaAuthentication;
    private javax.swing.JTextField tfieldName;
    private javax.swing.JTextField tfieldServerAddress;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
