/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.views;

/**
 *
 * @author iohangoncalves
 */
public class Execution extends javax.swing.JFrame {

    /**
     * Creates new form Execution
     */
    public Execution() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step1 = new javax.swing.JLabel();
        step2 = new javax.swing.JLabel();
        step3 = new javax.swing.JLabel();
        step4 = new javax.swing.JLabel();
        step5 = new javax.swing.JLabel();
        step6 = new javax.swing.JLabel();
        step7 = new javax.swing.JLabel();
        step8 = new javax.swing.JLabel();
        step9 = new javax.swing.JLabel();
        step10 = new javax.swing.JLabel();
        step11 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        step1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step0.png"))); // NOI18N
        getContentPane().add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, 100));

        step2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step1.png"))); // NOI18N
        getContentPane().add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        step3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step2.png"))); // NOI18N
        getContentPane().add(step3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        step4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step3.png"))); // NOI18N
        getContentPane().add(step4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        step5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step4.png"))); // NOI18N
        getContentPane().add(step5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        step6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step5.png"))); // NOI18N
        getContentPane().add(step6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        step7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step6.png"))); // NOI18N
        getContentPane().add(step7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        step8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step7.png"))); // NOI18N
        getContentPane().add(step8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        step9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step8.png"))); // NOI18N
        getContentPane().add(step9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        step10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step9.png"))); // NOI18N
        getContentPane().add(step10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 180, -1));

        step11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/step10.png"))); // NOI18N
        getContentPane().add(step11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/2000px-User_icon_2.svg.png"))); // NOI18N
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/cima.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/cimaDireita.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow9.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow8.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow8.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow8.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow7.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/arrow7.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/seta1.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesRunTime/seta1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Execution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Execution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Execution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Execution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Execution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel step1;
    private javax.swing.JLabel step10;
    private javax.swing.JLabel step11;
    private javax.swing.JLabel step2;
    private javax.swing.JLabel step3;
    private javax.swing.JLabel step4;
    private javax.swing.JLabel step5;
    private javax.swing.JLabel step6;
    private javax.swing.JLabel step7;
    private javax.swing.JLabel step8;
    private javax.swing.JLabel step9;
    // End of variables declaration//GEN-END:variables
}
